# Wrangler configuration for Cloudflare Pages deployment

name = "10x-project"
compatibility_date = "2025-08-15"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

[env.production]
name = "10x-project"

# Node.js compatibility is required for Supabase client

