-- migration: add table and column comments
-- purpose: provide documentation for database schema via postgres comments
-- affected tables: flashcards, study_sessions, ai_generation_batches
-- special considerations: comments visible in database tools and help maintain schema understanding

-- ============================================================================
-- table comments
-- ============================================================================

comment on table flashcards is
'stores flashcard content with 10-500 character front and 10-1000 character back limits (fr-005, fr-006). maximum 500 cards per user enforced at application level (fr-011).';

comment on table study_sessions is
'records study sessions for streak tracking (fr-021). completed sessions are used to calculate streaks on-demand via application logic.';

comment on table ai_generation_batches is
'tracks ai generation statistics to measure 75% acceptance rate target (success metrics). only accepted cards are stored in flashcards table.';

-- ============================================================================
-- column comments: flashcards
-- ============================================================================

comment on column flashcards.id is
'flashcard unique identifier';

comment on column flashcards.user_id is
'owner of the flashcard';

comment on column flashcards.generation_batch_id is
'links ai-generated cards to their batch for tracking acceptance metrics. null for manually created cards.';

comment on column flashcards.front_text is
'front side content (10-500 characters, fr-005)';

comment on column flashcards.back_text is
'back side content (10-1000 characters, fr-006)';

comment on column flashcards.is_ai_generated is
'indicates if card was ai-generated';

comment on column flashcards.was_edited is
'tracks if ai-generated card was modified during review or if any card was edited post-creation';

comment on column flashcards.created_at is
'creation timestamp';

comment on column flashcards.updated_at is
'last update timestamp';

-- ============================================================================
-- column comments: study_sessions
-- ============================================================================

comment on column study_sessions.id is
'session unique identifier';

comment on column study_sessions.user_id is
'user who conducted the session';

comment on column study_sessions.started_at is
'session start timestamp';

comment on column study_sessions.completed_at is
'session completion timestamp. null indicates incomplete/abandoned session. only completed sessions count toward streak.';

comment on column study_sessions.cards_studied is
'number of cards reviewed in session';

-- ============================================================================
-- column comments: ai_generation_batches
-- ============================================================================

comment on column ai_generation_batches.id is
'batch unique identifier';

comment on column ai_generation_batches.user_id is
'user who requested generation';

comment on column ai_generation_batches.generated_at is
'generation timestamp';

comment on column ai_generation_batches.input_text_length is
'character count of input text';

comment on column ai_generation_batches.total_cards_generated is
'total cards generated by ai';

comment on column ai_generation_batches.cards_accepted is
'number of cards accepted by user. cards_accepted + cards_rejected = total_cards_generated.';

comment on column ai_generation_batches.cards_rejected is
'number of cards rejected by user. cards_accepted + cards_rejected = total_cards_generated.';

comment on column ai_generation_batches.cards_edited is
'number of cards edited before acceptance';

comment on column ai_generation_batches.time_taken_ms is
'generation time in milliseconds. null if not recorded.';

comment on column ai_generation_batches.model_used is
'ai model identifier (e.g., openrouter model name) for cost and performance tracking. null if not recorded.';
